// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhTMoPMatJEsM5NgbOFlVoRwF_AjoUpk4',
    appId: '1:813400258962:web:f798cc709a60b7ed9de94b',
    messagingSenderId: '813400258962',
    projectId: 'chat-1db02',
    authDomain: 'chat-1db02.firebaseapp.com',
    storageBucket: 'chat-1db02.appspot.com',
    measurementId: 'G-KNM16VXMRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXIjTQBpJVMr4C-ND-UVhoeG-DsJFDia4',
    appId: '1:813400258962:android:62b64fdbb0484d859de94b',
    messagingSenderId: '813400258962',
    projectId: 'chat-1db02',
    storageBucket: 'chat-1db02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdif_1sWkmgThuTglNFdz0f5c9_twvV44',
    appId: '1:813400258962:ios:b05e8ad7d8652ae19de94b',
    messagingSenderId: '813400258962',
    projectId: 'chat-1db02',
    storageBucket: 'chat-1db02.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdif_1sWkmgThuTglNFdz0f5c9_twvV44',
    appId: '1:813400258962:ios:b05e8ad7d8652ae19de94b',
    messagingSenderId: '813400258962',
    projectId: 'chat-1db02',
    storageBucket: 'chat-1db02.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhTMoPMatJEsM5NgbOFlVoRwF_AjoUpk4',
    appId: '1:813400258962:web:e25c3968067df0c99de94b',
    messagingSenderId: '813400258962',
    projectId: 'chat-1db02',
    authDomain: 'chat-1db02.firebaseapp.com',
    storageBucket: 'chat-1db02.appspot.com',
    measurementId: 'G-KS08E0JLS1',
  );
}
